name: dartnow
version: 0.0.1
author: Dart Team <misc@dartlang.org>
description: Dart Now!
homepage: https://github.com/dart-lang/dart-pad
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  dart_to_js_script_rewriter: any
  codemirror: '>=0.2.3 <0.3.0'
  _discoveryapis_commons: '>=0.1.0 <0.2.0'
  http: '>=0.11.1 <0.12.0'
transformers:
- dart_to_js_script_rewriter